version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    image: mysql:latest
    platform: linux/amd64
    # volumes:
    #   - ./mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:3318:3306

  web:
    build: 
      context: .
      dockerfile: ./infra/python/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8555
    volumes:
      - .:/code
    ports:
      - "8555:8100"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '127.0.0.1:8777:80'
    environment:
      - PMA_HOST=mysql
      # - PMA_USER=root
      # - PMA_PASSWORD=password
    depends_on:
      - mysql

volumes:
  mysql_data: # データ永続化のため